name: CI

# ...

jobs:
  build:
    # ...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI 
        run: |
                mkdir -p ~/cli/sf
                wget -qO- https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz | tar xJ -C ~/cli/sf --strip-components 1
                export PATH=~/cli/sf/bin:$PATH
                echo "$PATH" >> $GITHUB_PATH
                echo "path is : ${PATH}"
                echo "github path is : ${GITHUB_PATH}"
                sf --version
                

      - name:  Run PMD Scanner
        run: |
           #sf scanner run --target force-app --outfile --help
           sf scanner run --target force-app --format html --outfile results.html
           ls -al

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload PMD Scanner reports
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: ./results.html
     
      - name: Run Tests
        run: <run the tests with code coverage>

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          # location of the coverage artifacts
          path: ./results.html

  deploy-coverage:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    
    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
